import Home from './components/Home'
import Login from './components/Login/Login'
import SignUp from './components/SignUp/SignUp'
import PrivateRoute from './components/PrivateRoute/PrivateRoute'
import{BrowserRouter as Router, Route, Routes, Navigate} from 'react-router-dom'
import Nav from './components/Nav/Nav'
import Profile from './components/Profile/Profile' 
import News from './components/News/News'
import ArticleDetails from './components/News/ArticleDetails'
